/**
 * 🇪🇺 EUROPE AIRPORTS DATABASE
 * Comprehensive database of major European airports with complete metadata
 * Covers all European regions: Western, Eastern, Northern, Southern Europe
 */

export interface EuropeAirport {
  iataCode: string;
  icaoCode: string;
  name: string;
  city: string;
  country: 'United Kingdom' | 'Germany' | 'France' | 'Spain' | 'Italy' | 'Netherlands' | 
           'Switzerland' | 'Austria' | 'Belgium' | 'Portugal' | 'Ireland' | 'Greece' |
           'Poland' | 'Czech Republic' | 'Hungary' | 'Romania' | 'Bulgaria' | 'Croatia' |
           'Slovenia' | 'Slovakia' | 'Lithuania' | 'Latvia' | 'Estonia' | 'Finland' |
           'Sweden' | 'Norway' | 'Denmark' | 'Iceland' | 'Luxembourg' | 'Malta' |
           'Cyprus' | 'Serbia' | 'Bosnia and Herzegovina' | 'Montenegro' | 'North Macedonia' |
           'Albania' | 'Moldova' | 'Belarus' | 'Ukraine' | 'Russia' | 'Turkey';
  countryCode: string;
  region: 'Western Europe' | 'Eastern Europe' | 'Northern Europe' | 'Southern Europe';
  timezone: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  elevation: number;
  runways: number;
  terminals: number;
  passengerCount: number; // millions per year
  cargoTonnage: number; // thousands of tons per year
  isInternational: boolean;
  category: 'major_hub' | 'hub' | 'international_gateway' | 'regional' | 'small_hub';
  primaryLanguages: string[];
  currency: string;
  searchKeywords: string[];
  popularDestinations: string[];
  airlinesCount: number;
  hasMetroConnection: boolean;
  distanceToCity: number; // km
}

export const EUROPE_AIRPORTS_DATABASE: EuropeAirport[] = [
  // WESTERN EUROPE - Major Aviation Hubs
  {
    iataCode: 'LHR',
    icaoCode: 'EGLL',
    name: 'London Heathrow Airport',
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Western Europe',
    timezone: 'Europe/London',
    coordinates: { latitude: 51.4700, longitude: -0.4543 },
    elevation: 25,
    runways: 2,
    terminals: 5,
    passengerCount: 79.2,
    cargoTonnage: 1760,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['English'],
    currency: 'GBP',
    searchKeywords: ['Heathrow', 'London', 'LHR', 'UK', 'Britain', 'England'],
    popularDestinations: ['JFK', 'DXB', 'CDG', 'FRA', 'AMS', 'MAD', 'BCN'],
    airlinesCount: 89,
    hasMetroConnection: true,
    distanceToCity: 24
  },
  {
    iataCode: 'CDG',
    icaoCode: 'LFPG',
    name: 'Charles de Gaulle Airport',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    region: 'Western Europe',
    timezone: 'Europe/Paris',
    coordinates: { latitude: 49.0097, longitude: 2.5479 },
    elevation: 119,
    runways: 4,
    terminals: 3,
    passengerCount: 76.2,
    cargoTonnage: 2102,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['French', 'English'],
    currency: 'EUR',
    searchKeywords: ['Charles de Gaulle', 'CDG', 'Paris', 'France', 'Roissy'],
    popularDestinations: ['JFK', 'DXB', 'LHR', 'FRA', 'AMS', 'BCN', 'MAD'],
    airlinesCount: 105,
    hasMetroConnection: true,
    distanceToCity: 32
  },
  {
    iataCode: 'FRA',
    icaoCode: 'EDDF',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Western Europe',
    timezone: 'Europe/Berlin',
    coordinates: { latitude: 50.0264, longitude: 8.5431 },
    elevation: 111,
    runways: 4,
    terminals: 2,
    passengerCount: 70.6,
    cargoTonnage: 2076,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['German', 'English'],
    currency: 'EUR',
    searchKeywords: ['Frankfurt', 'FRA', 'Germany', 'Main', 'Rhein-Main'],
    popularDestinations: ['JFK', 'DXB', 'LHR', 'CDG', 'MUC', 'AMS', 'ZUR'],
    airlinesCount: 142,
    hasMetroConnection: true,
    distanceToCity: 12
  },
  {
    iataCode: 'AMS',
    icaoCode: 'EHAM',
    name: 'Amsterdam Airport Schiphol',
    city: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Western Europe',
    timezone: 'Europe/Amsterdam',
    coordinates: { latitude: 52.3086, longitude: 4.7639 },
    elevation: -11,
    runways: 6,
    terminals: 1,
    passengerCount: 71.7,
    cargoTonnage: 1745,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['Dutch', 'English'],
    currency: 'EUR',
    searchKeywords: ['Schiphol', 'Amsterdam', 'AMS', 'Netherlands', 'Holland'],
    popularDestinations: ['JFK', 'DXB', 'LHR', 'CDG', 'FRA', 'BCN', 'MAD'],
    airlinesCount: 97,
    hasMetroConnection: true,
    distanceToCity: 17
  },
  {
    iataCode: 'MAD',
    icaoCode: 'LEMD',
    name: 'Adolfo Suárez Madrid-Barajas Airport',
    city: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Western Europe',
    timezone: 'Europe/Madrid',
    coordinates: { latitude: 40.4719, longitude: -3.5626 },
    elevation: 610,
    runways: 4,
    terminals: 4,
    passengerCount: 60.1,
    cargoTonnage: 557,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['Spanish', 'English'],
    currency: 'EUR',
    searchKeywords: ['Madrid', 'Barajas', 'MAD', 'Spain', 'España'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'FCO', 'BCN', 'LIS'],
    airlinesCount: 78,
    hasMetroConnection: true,
    distanceToCity: 12
  },
  {
    iataCode: 'FCO',
    icaoCode: 'LIRF',
    name: 'Leonardo da Vinci-Fiumicino Airport',
    city: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Western Europe',
    timezone: 'Europe/Rome',
    coordinates: { latitude: 41.8003, longitude: 12.2389 },
    elevation: 13,
    runways: 4,
    terminals: 3,
    passengerCount: 43.5,
    cargoTonnage: 179,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['Italian', 'English'],
    currency: 'EUR',
    searchKeywords: ['Fiumicino', 'Rome', 'Roma', 'FCO', 'Italy', 'Leonardo da Vinci'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'MAD', 'DXB', 'MXP'],
    airlinesCount: 89,
    hasMetroConnection: true,
    distanceToCity: 32
  },
  {
    iataCode: 'LGW',
    icaoCode: 'EGKK',
    name: 'London Gatwick Airport',
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Western Europe',
    timezone: 'Europe/London',
    coordinates: { latitude: 51.1481, longitude: -0.1903 },
    elevation: 62,
    runways: 1,
    terminals: 2,
    passengerCount: 46.6,
    cargoTonnage: 111,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['English'],
    currency: 'GBP',
    searchKeywords: ['Gatwick', 'London', 'LGW', 'UK', 'Britain', 'England'],
    popularDestinations: ['JFK', 'DXB', 'BCN', 'MAD', 'AGP', 'PMI', 'FAO'],
    airlinesCount: 65,
    hasMetroConnection: true,
    distanceToCity: 48
  },
  {
    iataCode: 'MUC',
    icaoCode: 'EDDM',
    name: 'Munich Airport',
    city: 'Munich',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Western Europe',
    timezone: 'Europe/Berlin',
    coordinates: { latitude: 48.3538, longitude: 11.7861 },
    elevation: 453,
    runways: 2,
    terminals: 2,
    passengerCount: 47.9,
    cargoTonnage: 385,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['German', 'English'],
    currency: 'EUR',
    searchKeywords: ['Munich', 'München', 'MUC', 'Germany', 'Bayern', 'Bavaria'],
    popularDestinations: ['JFK', 'DXB', 'LHR', 'CDG', 'FRA', 'VIE', 'ZUR'],
    airlinesCount: 76,
    hasMetroConnection: true,
    distanceToCity: 37
  },
  {
    iataCode: 'BCN',
    icaoCode: 'LEBL',
    name: 'Josep Tarradellas Barcelona-El Prat Airport',
    city: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Western Europe',
    timezone: 'Europe/Madrid',
    coordinates: { latitude: 41.2971, longitude: 2.0785 },
    elevation: 4,
    runways: 3,
    terminals: 2,
    passengerCount: 52.7,
    cargoTonnage: 184,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Spanish', 'Catalan', 'English'],
    currency: 'EUR',
    searchKeywords: ['Barcelona', 'El Prat', 'BCN', 'Spain', 'Catalunya', 'Catalonia'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'MAD', 'FCO', 'LIS'],
    airlinesCount: 87,
    hasMetroConnection: true,
    distanceToCity: 17
  },
  {
    iataCode: 'ZUR',
    icaoCode: 'LSZH',
    name: 'Zurich Airport',
    city: 'Zurich',
    country: 'Switzerland',
    countryCode: 'CH',
    region: 'Western Europe',
    timezone: 'Europe/Zurich',
    coordinates: { latitude: 47.4647, longitude: 8.5492 },
    elevation: 436,
    runways: 3,
    terminals: 3,
    passengerCount: 31.1,
    cargoTonnage: 458,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['German', 'French', 'Italian', 'English'],
    currency: 'CHF',
    searchKeywords: ['Zurich', 'Zürich', 'ZUR', 'Switzerland', 'Schweiz', 'Kloten'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'MUC', 'VIE', 'GVA'],
    airlinesCount: 67,
    hasMetroConnection: true,
    distanceToCity: 13
  },
  {
    iataCode: 'VIE',
    icaoCode: 'LOWW',
    name: 'Vienna International Airport',
    city: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    region: 'Western Europe',
    timezone: 'Europe/Vienna',
    coordinates: { latitude: 48.1103, longitude: 16.5697 },
    elevation: 183,
    runways: 2,
    terminals: 4,
    passengerCount: 31.7,
    cargoTonnage: 327,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['German', 'English'],
    currency: 'EUR',
    searchKeywords: ['Vienna', 'Wien', 'VIE', 'Austria', 'Österreich', 'Schwechat'],
    popularDestinations: ['JFK', 'DXB', 'LHR', 'CDG', 'FRA', 'MUC', 'ZUR'],
    airlinesCount: 74,
    hasMetroConnection: true,
    distanceToCity: 18
  },
  {
    iataCode: 'BRU',
    icaoCode: 'EBBR',
    name: 'Brussels Airport',
    city: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    region: 'Western Europe',
    timezone: 'Europe/Brussels',
    coordinates: { latitude: 50.9014, longitude: 4.4844 },
    elevation: 56,
    runways: 3,
    terminals: 1,
    passengerCount: 26.4,
    cargoTonnage: 667,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Dutch', 'French', 'English'],
    currency: 'EUR',
    searchKeywords: ['Brussels', 'Bruxelles', 'Brussel', 'BRU', 'Belgium', 'Zaventem'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'AMS', 'DXB', 'MAD'],
    airlinesCount: 68,
    hasMetroConnection: true,
    distanceToCity: 12
  },

  // NORTHERN EUROPE - Scandinavian & Nordic Hubs
  {
    iataCode: 'ARN',
    icaoCode: 'ESSA',
    name: 'Stockholm Arlanda Airport',
    city: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    region: 'Northern Europe',
    timezone: 'Europe/Stockholm',
    coordinates: { latitude: 59.6519, longitude: 17.9186 },
    elevation: 42,
    runways: 4,
    terminals: 4,
    passengerCount: 26.8,
    cargoTonnage: 173,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Swedish', 'English'],
    currency: 'SEK',
    searchKeywords: ['Stockholm', 'Arlanda', 'ARN', 'Sweden', 'Sverige'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'CPH', 'OSL', 'HEL'],
    airlinesCount: 52,
    hasMetroConnection: true,
    distanceToCity: 37
  },
  {
    iataCode: 'CPH',
    icaoCode: 'EKCH',
    name: 'Copenhagen Airport',
    city: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    region: 'Northern Europe',
    timezone: 'Europe/Copenhagen',
    coordinates: { latitude: 55.6181, longitude: 12.6561 },
    elevation: 5,
    runways: 3,
    terminals: 3,
    passengerCount: 30.3,
    cargoTonnage: 365,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Danish', 'English'],
    currency: 'DKK',
    searchKeywords: ['Copenhagen', 'København', 'CPH', 'Denmark', 'Danmark', 'Kastrup'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'ARN', 'OSL', 'HEL'],
    airlinesCount: 64,
    hasMetroConnection: true,
    distanceToCity: 8
  },
  {
    iataCode: 'OSL',
    icaoCode: 'ENGM',
    name: 'Oslo Airport',
    city: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    region: 'Northern Europe',
    timezone: 'Europe/Oslo',
    coordinates: { latitude: 60.1939, longitude: 11.1004 },
    elevation: 202,
    runways: 2,
    terminals: 1,
    passengerCount: 28.6,
    cargoTonnage: 168,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Norwegian', 'English'],
    currency: 'NOK',
    searchKeywords: ['Oslo', 'OSL', 'Norway', 'Norge', 'Gardermoen'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'ARN', 'CPH', 'HEL'],
    airlinesCount: 47,
    hasMetroConnection: true,
    distanceToCity: 47
  },
  {
    iataCode: 'HEL',
    icaoCode: 'EFHK',
    name: 'Helsinki-Vantaa Airport',
    city: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    region: 'Northern Europe',
    timezone: 'Europe/Helsinki',
    coordinates: { latitude: 60.3172, longitude: 24.9633 },
    elevation: 55,
    runways: 3,
    terminals: 2,
    passengerCount: 20.8,
    cargoTonnage: 173,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Finnish', 'Swedish', 'English'],
    currency: 'EUR',
    searchKeywords: ['Helsinki', 'HEL', 'Finland', 'Suomi', 'Vantaa'],
    popularDestinations: ['JFK', 'NRT', 'PVG', 'LHR', 'CDG', 'FRA', 'ARN'],
    airlinesCount: 43,
    hasMetroConnection: true,
    distanceToCity: 19
  },
  {
    iataCode: 'KEF',
    icaoCode: 'BIKF',
    name: 'Keflavík International Airport',
    city: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    region: 'Northern Europe',
    timezone: 'Atlantic/Reykjavik',
    coordinates: { latitude: 63.9850, longitude: -22.6056 },
    elevation: 56,
    runways: 2,
    terminals: 1,
    passengerCount: 7.2,
    cargoTonnage: 84,
    isInternational: true,
    category: 'international_gateway',
    primaryLanguages: ['Icelandic', 'English'],
    currency: 'ISK',
    searchKeywords: ['Reykjavik', 'Keflavik', 'KEF', 'Iceland', 'Ísland'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'CPH', 'OSL', 'YYZ'],
    airlinesCount: 28,
    hasMetroConnection: false,
    distanceToCity: 50
  },

  // EASTERN EUROPE - Major Gateways
  {
    iataCode: 'WAW',
    icaoCode: 'EPWA',
    name: 'Warsaw Chopin Airport',
    city: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    region: 'Eastern Europe',
    timezone: 'Europe/Warsaw',
    coordinates: { latitude: 52.1657, longitude: 20.9671 },
    elevation: 110,
    runways: 2,
    terminals: 1,
    passengerCount: 18.9,
    cargoTonnage: 74,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Polish', 'English'],
    currency: 'PLN',
    searchKeywords: ['Warsaw', 'Warszawa', 'WAW', 'Poland', 'Polska', 'Chopin'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'AMS', 'PRG', 'BUD'],
    airlinesCount: 54,
    hasMetroConnection: true,
    distanceToCity: 10
  },
  {
    iataCode: 'PRG',
    icaoCode: 'LKPR',
    name: 'Václav Havel Airport Prague',
    city: 'Prague',
    country: 'Czech Republic',
    countryCode: 'CZ',
    region: 'Eastern Europe',
    timezone: 'Europe/Prague',
    coordinates: { latitude: 50.1008, longitude: 14.2600 },
    elevation: 380,
    runways: 2,
    terminals: 2,
    passengerCount: 17.8,
    cargoTonnage: 69,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Czech', 'English'],
    currency: 'CZK',
    searchKeywords: ['Prague', 'Praha', 'PRG', 'Czech Republic', 'Czechia', 'Václav Havel'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'AMS', 'WAW', 'BUD'],
    airlinesCount: 67,
    hasMetroConnection: true,
    distanceToCity: 17
  },
  {
    iataCode: 'BUD',
    icaoCode: 'LHBP',
    name: 'Budapest Ferenc Liszt International Airport',
    city: 'Budapest',
    country: 'Hungary',
    countryCode: 'HU',
    region: 'Eastern Europe',
    timezone: 'Europe/Budapest',
    coordinates: { latitude: 47.4297, longitude: 19.2611 },
    elevation: 151,
    runways: 2,
    terminals: 2,
    passengerCount: 16.2,
    cargoTonnage: 93,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Hungarian', 'English'],
    currency: 'HUF',
    searchKeywords: ['Budapest', 'BUD', 'Hungary', 'Magyarország', 'Ferenc Liszt'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'AMS', 'WAW', 'PRG'],
    airlinesCount: 48,
    hasMetroConnection: true,
    distanceToCity: 16
  },
  {
    iataCode: 'OTP',
    icaoCode: 'LROP',
    name: 'Henri Coandă International Airport',
    city: 'Bucharest',
    country: 'Romania',
    countryCode: 'RO',
    region: 'Eastern Europe',
    timezone: 'Europe/Bucharest',
    coordinates: { latitude: 44.5711, longitude: 26.0850 },
    elevation: 95,
    runways: 2,
    terminals: 1,
    passengerCount: 14.7,
    cargoTonnage: 43,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Romanian', 'English'],
    currency: 'RON',
    searchKeywords: ['Bucharest', 'București', 'OTP', 'Romania', 'România', 'Henri Coandă'],
    popularDestinations: ['LHR', 'CDG', 'FRA', 'AMS', 'WAW', 'VIE', 'IST'],
    airlinesCount: 43,
    hasMetroConnection: false,
    distanceToCity: 16
  },

  // SOUTHERN EUROPE - Mediterranean Gateways
  {
    iataCode: 'ATH',
    icaoCode: 'LGAV',
    name: 'Athens International Airport',
    city: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    region: 'Southern Europe',
    timezone: 'Europe/Athens',
    coordinates: { latitude: 37.9364, longitude: 23.9445 },
    elevation: 94,
    runways: 2,
    terminals: 1,
    passengerCount: 25.6,
    cargoTonnage: 89,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Greek', 'English'],
    currency: 'EUR',
    searchKeywords: ['Athens', 'Αθήνα', 'ATH', 'Greece', 'Ελλάδα', 'Spata'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'FCO', 'DXB', 'IST'],
    airlinesCount: 67,
    hasMetroConnection: true,
    distanceToCity: 33
  },
  {
    iataCode: 'LIS',
    icaoCode: 'LPPT',
    name: 'Lisbon Airport',
    city: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    region: 'Southern Europe',
    timezone: 'Europe/Lisbon',
    coordinates: { latitude: 38.7813, longitude: -9.1357 },
    elevation: 114,
    runways: 2,
    terminals: 2,
    passengerCount: 31.2,
    cargoTonnage: 128,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Portuguese', 'English'],
    currency: 'EUR',
    searchKeywords: ['Lisbon', 'Lisboa', 'LIS', 'Portugal', 'Portela'],
    popularDestinations: ['JFK', 'GIG', 'MAD', 'CDG', 'LHR', 'FRA', 'FCO'],
    airlinesCount: 72,
    hasMetroConnection: true,
    distanceToCity: 7
  },
  {
    iataCode: 'MXP',
    icaoCode: 'LIMC',
    name: 'Milan Malpensa Airport',
    city: 'Milan',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Southern Europe',
    timezone: 'Europe/Rome',
    coordinates: { latitude: 45.6301, longitude: 8.7231 },
    elevation: 234,
    runways: 2,
    terminals: 2,
    passengerCount: 28.8,
    cargoTonnage: 651,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['Italian', 'English'],
    currency: 'EUR',
    searchKeywords: ['Milan', 'Milano', 'MXP', 'Italy', 'Italia', 'Malpensa'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'FCO', 'DXB', 'ZUR'],
    airlinesCount: 76,
    hasMetroConnection: true,
    distanceToCity: 49
  },
  {
    iataCode: 'IST',
    icaoCode: 'LTFM',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    region: 'Southern Europe',
    timezone: 'Europe/Istanbul',
    coordinates: { latitude: 41.2753, longitude: 28.7519 },
    elevation: 119,
    runways: 5,
    terminals: 1,
    passengerCount: 76.0,
    cargoTonnage: 1540,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['Turkish', 'English'],
    currency: 'TRY',
    searchKeywords: ['Istanbul', 'İstanbul', 'IST', 'Turkey', 'Türkiye'],
    popularDestinations: ['JFK', 'DXB', 'LHR', 'CDG', 'FRA', 'DOH', 'KWI'],
    airlinesCount: 95,
    hasMetroConnection: true,
    distanceToCity: 42
  },

  // ADDITIONAL MAJOR EUROPEAN HUBS
  {
    iataCode: 'DUB',
    icaoCode: 'EIDW',
    name: 'Dublin Airport',
    city: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    region: 'Western Europe',
    timezone: 'Europe/Dublin',
    coordinates: { latitude: 53.4213, longitude: -6.2701 },
    elevation: 74,
    runways: 2,
    terminals: 2,
    passengerCount: 32.9,
    cargoTonnage: 156,
    isInternational: true,
    category: 'hub',
    primaryLanguages: ['English', 'Irish'],
    currency: 'EUR',
    searchKeywords: ['Dublin', 'DUB', 'Ireland', 'Éire'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'AMS', 'MAD', 'BCN'],
    airlinesCount: 67,
    hasMetroConnection: false,
    distanceToCity: 10
  },
  {
    iataCode: 'SVO',
    icaoCode: 'UUEE',
    name: 'Sheremetyevo International Airport',
    city: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    region: 'Eastern Europe',
    timezone: 'Europe/Moscow',
    coordinates: { latitude: 55.9728, longitude: 37.4147 },
    elevation: 190,
    runways: 3,
    terminals: 6,
    passengerCount: 49.9,
    cargoTonnage: 278,
    isInternational: true,
    category: 'major_hub',
    primaryLanguages: ['Russian', 'English'],
    currency: 'RUB',
    searchKeywords: ['Moscow', 'Москва', 'SVO', 'Russia', 'Россия', 'Sheremetyevo'],
    popularDestinations: ['PEK', 'LED', 'KJA', 'SVX', 'ROV', 'VKO', 'DME'],
    airlinesCount: 73,
    hasMetroConnection: true,
    distanceToCity: 29
  },
  {
    iataCode: 'ZAG',
    icaoCode: 'LDZA',
    name: 'Zagreb Airport',
    city: 'Zagreb',
    country: 'Croatia',
    countryCode: 'HR',
    region: 'Eastern Europe',
    timezone: 'Europe/Zagreb',
    coordinates: { latitude: 45.7429, longitude: 16.0688 },
    elevation: 108,
    runways: 1,
    terminals: 1,
    passengerCount: 3.4,
    cargoTonnage: 12,
    isInternational: true,
    category: 'regional',
    primaryLanguages: ['Croatian', 'English'],
    currency: 'EUR',
    searchKeywords: ['Zagreb', 'ZAG', 'Croatia', 'Hrvatska'],
    popularDestinations: ['LHR', 'CDG', 'FRA', 'AMS', 'VIE', 'MUC', 'FCO'],
    airlinesCount: 34,
    hasMetroConnection: false,
    distanceToCity: 17
  },
  {
    iataCode: 'LUX',
    icaoCode: 'ELLX',
    name: 'Luxembourg Airport',
    city: 'Luxembourg',
    country: 'Luxembourg',
    countryCode: 'LU',
    region: 'Western Europe',
    timezone: 'Europe/Luxembourg',
    coordinates: { latitude: 49.6233, longitude: 6.2044 },
    elevation: 376,
    runways: 1,
    terminals: 1,
    passengerCount: 4.4,
    cargoTonnage: 971,
    isInternational: true,
    category: 'regional',
    primaryLanguages: ['Luxembourgish', 'French', 'German', 'English'],
    currency: 'EUR',
    searchKeywords: ['Luxembourg', 'LUX', 'Lëtzebuerg'],
    popularDestinations: ['JFK', 'LHR', 'CDG', 'FRA', 'AMS', 'ZUR', 'VIE'],
    airlinesCount: 23,
    hasMetroConnection: false,
    distanceToCity: 6
  },
  {
    iataCode: 'MLA',
    icaoCode: 'LMML',
    name: 'Malta International Airport',
    city: 'Valletta',
    country: 'Malta',
    countryCode: 'MT',
    region: 'Southern Europe',
    timezone: 'Europe/Malta',
    coordinates: { latitude: 35.8575, longitude: 14.4775 },
    elevation: 91,
    runways: 1,
    terminals: 1,
    passengerCount: 7.3,
    cargoTonnage: 18,
    isInternational: true,
    category: 'regional',
    primaryLanguages: ['Maltese', 'English'],
    currency: 'EUR',
    searchKeywords: ['Malta', 'MLA', 'Valletta'],
    popularDestinations: ['LHR', 'CDG', 'FRA', 'FCO', 'ATH', 'IST', 'CAI'],
    airlinesCount: 28,
    hasMetroConnection: false,
    distanceToCity: 8
  },
  {
    iataCode: 'LCA',
    icaoCode: 'LCLK',
    name: 'Larnaca International Airport',
    city: 'Larnaca',
    country: 'Cyprus',
    countryCode: 'CY',
    region: 'Southern Europe',
    timezone: 'Asia/Nicosia',
    coordinates: { latitude: 34.8751, longitude: 33.6249 },
    elevation: 8,
    runways: 2,
    terminals: 1,
    passengerCount: 8.2,
    cargoTonnage: 31,
    isInternational: true,
    category: 'regional',
    primaryLanguages: ['Greek', 'Turkish', 'English'],
    currency: 'EUR',
    searchKeywords: ['Larnaca', 'LCA', 'Cyprus', 'Κύπρος'],
    popularDestinations: ['LHR', 'CDG', 'FRA', 'ATH', 'IST', 'CAI', 'TLV'],
    airlinesCount: 32,
    hasMetroConnection: false,
    distanceToCity: 5
  }
];

export function createEuropeAirportSearchIndex(): Map<string, EuropeAirport[]> {
  const index = new Map<string, EuropeAirport[]>();
  
  EUROPE_AIRPORTS_DATABASE.forEach(airport => {
    // Index by IATA code
    const iataKey = airport.iataCode.toLowerCase();
    if (!index.has(iataKey)) index.set(iataKey, []);
    index.get(iataKey)!.push(airport);
    
    // Index by city (normalized)
    const cityKey = airport.city.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    if (!index.has(cityKey)) index.set(cityKey, []);
    index.get(cityKey)!.push(airport);
    
    // Index by country
    const countryKey = airport.country.toLowerCase();
    if (!index.has(countryKey)) index.set(countryKey, []);
    index.get(countryKey)!.push(airport);
    
    // Index by keywords
    airport.searchKeywords.forEach(keyword => {
      const keywordKey = keyword.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      if (!index.has(keywordKey)) index.set(keywordKey, []);
      index.get(keywordKey)!.push(airport);
    });
  });
  
  return index;
}

export const EUROPE_AIRPORTS_BY_REGION = {
  'Western Europe': EUROPE_AIRPORTS_DATABASE.filter(a => a.region === 'Western Europe'),
  'Eastern Europe': EUROPE_AIRPORTS_DATABASE.filter(a => a.region === 'Eastern Europe'), 
  'Northern Europe': EUROPE_AIRPORTS_DATABASE.filter(a => a.region === 'Northern Europe'),
  'Southern Europe': EUROPE_AIRPORTS_DATABASE.filter(a => a.region === 'Southern Europe')
};

export const EUROPE_MAJOR_HUBS = EUROPE_AIRPORTS_DATABASE.filter(
  airport => airport.category === 'major_hub'
);

export const EUROPE_INTERNATIONAL_GATEWAYS = EUROPE_AIRPORTS_DATABASE.filter(
  airport => airport.isInternational && ['major_hub', 'hub', 'international_gateway'].includes(airport.category)
);