/**
 * SITEMAP INDEX - /sitemap-index.xml
 * Master sitemap referencing all sub-sitemaps
 *
 * Structure:
 * - /sitemap.xml → Core pages (auto-generated by Next.js)
 * - /sitemaps/routes.xml → 10,000+ flight routes
 * - /sitemaps/cities.xml → City pages
 * - /sitemaps/destinations.xml → Destinations, deals, airlines, World Cup
 * - /sitemaps/blog.xml → Blog & content pages
 */

import { NextResponse } from 'next/server';

export const dynamic = 'force-static';
export const revalidate = 86400;

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://www.fly2any.com';
const today = new Date().toISOString().split('T')[0];

export async function GET() {
  const sitemaps = [
    { loc: `${SITE_URL}/sitemap.xml` },
    { loc: `${SITE_URL}/sitemaps/routes.xml` },
    { loc: `${SITE_URL}/sitemaps/cities.xml` },
    { loc: `${SITE_URL}/sitemaps/destinations.xml` },
    { loc: `${SITE_URL}/sitemaps/deals.xml` },
    { loc: `${SITE_URL}/sitemaps/blog.xml` },
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemaps
  .map(
    (sm) => `  <sitemap>
    <loc>${sm.loc}</loc>
    <lastmod>${today}</lastmod>
  </sitemap>`
  )
  .join('\n')}
</sitemapindex>`;

  return new NextResponse(xml, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
