-- Add missing columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP(3);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "timezone" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
